#+TITLE: STM32L0 test
#+DATE: <2015-11-22 v>
#+AUTHOR: Kalicz Péter
#+EMAIL: kaliczp@emk.nyme.hu
#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t c:nil creator:comment d:(not "LOGBOOK") date:t
#+OPTIONS: e:t email:nil f:t inline:t num:t p:nil pri:nil stat:t
#+OPTIONS: tags:t tasks:t tex:t timestamp:t toc:t todo:t |:t
#+CREATOR: Emacs 24.4.1 (Org mode 8.2.10)
#+DESCRIPTION:
#+EXCLUDE_TAGS: noexport
#+KEYWORDS:
#+LANGUAGE: en
#+SELECT_TAGS: export

* Bugs

** DONE BOOT0 to GND
trough a 10k resistor. See the ref. design. Boot from Flash.
Is there 10k resistor in 0805 package?

** DONE GND PIN to the USART1

** DONE TX RX silkscreen

** DONE Supply in is too close to SWD connector

* Qestions

- If I use internal temperature sensor to estimate the ambient
  environment temperature is it necessary to use ferrite bead?
  I will use it.
- How connect design to ST-LINK?
  I will use HEADER10_2 more-or-less standard
- Which pins are SPI capable?
  PB3:PB5
- Which pins are (low power) USART capable?
  STM32L051K8Tx has no LPUART. PB6:PB7 seems to best.
  In the case hardware flow control PA8:PA12
- How can I set up external interrupt?
  PA0 or any GPIO_EXTI pins
- Type and voltage characteristic of Li-ion primary battery?
  3.6V Lithium Thionyl Chloride (Li-SOCl2) Batterie
  XENO XL-060F [[http://www.xenoenergy.com/eng/prod/genaral03.asp]]
  2.4 Ah at 2mA
- STM32L0 debug OK?
  Through ARM SWDI works well.

* Plan

** Power
Power source from primary Li-ion battery directly (3.6 V) or two
rechargeable Ni-MH battery (2.4 V).
Li-ion primary battery is OK. E.g. in the Cube example.

** RTC
Measure time with RTC. Calibrate RTC crystal with internal
thermometer. Measure bi-hourly.
0603 size capacitors 2-12 nF

** Data storage
Use SPI EEPROM as a storage place. Store BCD data.
100k resistor (0805 or 2012 metric) Available.

** Sensors

*** Reed relay
Reed relay as a data source with interrupt. Permanent magnet (super)
on tiping bucket.

*** Weighing sensor
1 kg

*** Soil temperature meter

*** Humidity temperature meter
