#+TITLE: STM32L0 test
#+DATE: <2015-11-22 v>
#+AUTHOR: Kalicz Péter
#+EMAIL: kaliczp@emk.nyme.hu
#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t c:nil creator:comment d:(not "LOGBOOK") date:t
#+OPTIONS: e:t email:nil f:t inline:t num:t p:nil pri:nil stat:t
#+OPTIONS: tags:t tasks:t tex:t timestamp:t toc:t todo:t |:t
#+CREATOR: Emacs 24.4.1 (Org mode 8.2.10)
#+DESCRIPTION:
#+EXCLUDE_TAGS: noexport
#+KEYWORDS:
#+LANGUAGE: en
#+SELECT_TAGS: export

* Bugs

** TODO GND PIN to the USART1
Earlier included now neccessary?

* Suggestions

** TODO Connectors
It would be nice to use unchangeable connectors.

** TODO Reset
Somehow would be good to make reset or enough to use st-util?

** DONE Capacitor modification
Larger capacitor for MCU is wery close to MCU that side
is not easily solderable.

* Qestions

- If I use internal temperature sensor to estimate the ambient
  environment temperature is it necessary to use ferrite bead?
  I will use it.
- Type and voltage characteristic of Li-ion primary battery?
  3.6V Lithium Thionyl Chloride (Li-SOCl2) Batterie
  XENO XL-060F [[http://www.xenoenergy.com/eng/prod/genaral03.asp]]
  2.4 Ah at 2mA

* Plan

** Power
Power source from primary Li-ion battery directly (3.6 V) or two
rechargeable Ni-MH battery (2.4 V).
Li-ion primary battery is OK. E.g. in the Cube example.

** RTC
Measure time with RTC. Calibrate RTC crystal with internal
thermometer. Measure bi-hourly.
0603 size capacitors 2-12 nF

** Data storage
Use SPI EEPROM as a storage place. Store BCD data.
100k resistor (0805 or 2012 metric) Available.

** Sensors

*** Reed relay
Reed relay as a data source with interrupt. Permanent magnet (super)
on tiping bucket.

*** Weighing sensor
1 kg

*** Soil temperature meter

*** Humidity temperature meter
